[CmdletBinding()]
param([string]$InstallRoot="$HOME/fieldora-server",[string]$FieldoraRef="security/native-update-trust-hardening",[string]$BastionRef="main",[string]$AdminUsername="admin",[string]$AdminName="Administrator",[string]$Organization="local",[string]$AdminPassword="")
Set-StrictMode -Version Latest
$ErrorActionPreference="Stop";$ProgressPreference="SilentlyContinue"
function Step([string]$Text){Write-Host "`n============================================================" -ForegroundColor DarkCyan;Write-Host "==> $Text" -ForegroundColor Cyan;Write-Host "============================================================" -ForegroundColor DarkCyan}
function Download-RepoArchive([string]$Repository,[string]$Ref,[string]$Destination){$t=[IO.Path]::GetTempPath();$safe=($Repository-replace'[^A-Za-z0-9._-]','-');$zip=Join-Path $t "$safe.zip";$ex=Join-Path $t "$safe-extract";Remove-Item $zip -Force -ErrorAction SilentlyContinue;Remove-Item $ex -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force -Path $ex|Out-Null;$r=[Uri]::EscapeDataString($Ref);$u="https://github.com/$Repository/archive/refs/heads/$r.zip";if($Ref-match'^[0-9a-fA-F]{40}$'){$u="https://github.com/$Repository/archive/$Ref.zip"};Invoke-WebRequest $u -OutFile $zip -UseBasicParsing;Expand-Archive $zip $ex -Force;$s=Get-ChildItem $ex -Directory|Select-Object -First 1;if(-not$s){throw"Unable to extract $Repository@$Ref"};Remove-Item $Destination -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force -Path $Destination|Out-Null;Get-ChildItem $s.FullName -Force|%{Copy-Item $_.FullName $Destination -Recurse -Force};Remove-Item $zip -Force;Remove-Item $ex -Recurse -Force}
if(-not$IsLinux){throw'This complete installer is for a Linux Docker host.'};if($PSVersionTable.PSVersion.Major-lt7){throw'PowerShell 7+ required.'};foreach($c in @('docker','curl')){if(-not(Get-Command $c -ErrorAction SilentlyContinue)){throw"$c is required."}};& docker info *> $null;if($LASTEXITCODE-ne0){throw'Docker Engine is not running.'};& docker compose version *> $null;if($LASTEXITCODE-ne0){throw'Docker Compose v2 is required.'}
$InstallRoot=[IO.Path]::GetFullPath($InstallRoot);$BastionRoot=Join-Path $InstallRoot 'bastion';Write-Host 'Fieldora Complete Docker Installer' -ForegroundColor Green;Write-Host "Fieldora : Natuurgids/Fieldora@$FieldoraRef";Write-Host "Bastion  : Natuurgids/FieldoraBastion@$BastionRef";Write-Host "Root     : $InstallRoot";Write-Host 'Installs the Fieldora server stack and separate FieldoraBastion security boundary.' -ForegroundColor Yellow;if((Read-Host 'Type CLEAN to continue').Trim().ToUpperInvariant()-ne'CLEAN'){exit 0}
Step 'Installing Fieldora server stack';$t=[IO.Path]::GetTempPath();$w=Join-Path $t 'Install-Fieldora-Clean-Linux.ps1';Invoke-WebRequest "https://raw.githubusercontent.com/Natuurgids/Fieldora/$FieldoraRef/Install-Fieldora-Clean-Linux.ps1" -OutFile $w -UseBasicParsing;'CLEAN'|& $w -InstallRoot $InstallRoot -FieldoraRef $FieldoraRef -AdminUsername $AdminUsername -AdminName $AdminName -Organization $Organization -AdminPassword $AdminPassword;if($LASTEXITCODE-ne0){throw'Fieldora server installation failed.'}
Step 'Installing FieldoraBastion';Download-RepoArchive 'Natuurgids/FieldoraBastion' $BastionRef $BastionRoot;if(-not(Test-Path (Join-Path $BastionRoot 'compose.yaml'))){throw'Bastion compose.yaml missing.'};Push-Location $BastionRoot;try{& docker compose config *> $null;if($LASTEXITCODE-ne0){throw'Bastion compose invalid.'};& docker compose build;if($LASTEXITCODE-ne0){throw'Bastion build failed.'};& docker compose up -d;if($LASTEXITCODE-ne0){throw'Bastion startup failed.'};& docker compose ps}finally{Pop-Location}
Step 'Verifying Fieldora';$ca=Join-Path $InstallRoot 'service-trust/ca-certificate.pem';if(-not(Test-Path $ca)){throw'Fieldora service CA missing.'};& curl --fail --silent --show-error --cacert $ca https://127.0.0.1:8765/health/live *> $null;if($LASTEXITCODE-ne0){throw'Fieldora live health failed.'};& curl --fail --silent --show-error --cacert $ca https://127.0.0.1:8765/health/ready *> $null;if($LASTEXITCODE-ne0){throw'Fieldora readiness failed.'}
Step 'Installation complete';Write-Host "Fieldora server root : $InstallRoot" -ForegroundColor Green;Write-Host "FieldoraBastion root : $BastionRoot" -ForegroundColor Green;Write-Host 'Bastion remains a separate security domain and receives no Fieldora database credentials.' -ForegroundColor Green
