"""Persistence boundary for Phase E desktop synchronization configuration."""

from __future__ import annotations

from typing import Protocol

from natureai_next.domain.synchronization import (
    PlatformAccount,
    ProjectEnrollment,
    RegisteredDesktopDevice,
    SyncChange,
    SyncConflict,
    MediaTransfer,
    ContributionAcknowledgment,
)


class DesktopSynchronizationRepository(Protocol):
    def put_account(self, account: PlatformAccount) -> None: ...
    def accounts(self) -> tuple[PlatformAccount, ...]: ...
    def put_device(self, device: RegisteredDesktopDevice) -> None: ...
    def devices(self, account_id: str) -> tuple[RegisteredDesktopDevice, ...]: ...
    def put_enrollment(self, enrollment: ProjectEnrollment) -> None: ...
    def enrollments(self, account_id: str) -> tuple[ProjectEnrollment, ...]: ...
    def enqueue_outbox(self, change: SyncChange) -> bool: ...
    def claim_outbox(
        self, *, enrollment_id: str, now_utc: str, lease_until_utc: str, limit: int
    ) -> tuple[SyncChange, ...]: ...
    def retry_outbox(self, change_id: str, *, next_attempt_at_utc: str) -> None: ...
    def complete_outbox(self, change_id: str) -> None: ...
    def stop_outbox(self, change_id: str, *, state: str) -> None: ...
    def accept_inbox(self, change: SyncChange) -> bool: ...
    def put_cursor(self, enrollment_id: str, cursor: str) -> None: ...
    def cursor(self, enrollment_id: str) -> str: ...
    def put_conflict(self, conflict: SyncConflict) -> None: ...
    def conflicts(self, enrollment_id: str) -> tuple[SyncConflict, ...]: ...
    def put_media_transfer(self, transfer: MediaTransfer) -> None: ...
    def media_transfer(self, transfer_id: str) -> MediaTransfer | None: ...
    def acknowledge_contribution(self, acknowledgment: ContributionAcknowledgment) -> None: ...
    def has_current_acknowledgment(self, enrollment_id: str, revision: int) -> bool: ...
    def pending_outbox(self, enrollment_id: str) -> tuple[SyncChange, ...]: ...
    def resolve_conflict(
        self, conflict_id: str, *, resolution: str, payload: dict, resolved_at_utc: str
    ) -> None: ...
