"""PostgreSQL clean-install schema for asset/equipment/facility operations."""
from __future__ import annotations
from collections.abc import Callable
from typing import Any

class PostgresOperationsSchema:
    def __init__(self, connect: Callable[[], Any]) -> None:
        self._connect=connect;self.ensure_schema()
    @staticmethod
    def statements():
        return [
"""CREATE TABLE IF NOT EXISTS ops_locations(id UUID PRIMARY KEY,parent_id UUID REFERENCES ops_locations(id),location_type TEXT NOT NULL,code TEXT NOT NULL,name TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',drawing_id UUID,sort_order INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL,UNIQUE(parent_id,code))""",
"""CREATE TABLE IF NOT EXISTS ops_storage_conditions(id UUID PRIMARY KEY,location_id UUID REFERENCES ops_locations(id) ON DELETE CASCADE,name TEXT NOT NULL,temperature_min DOUBLE PRECISION,temperature_max DOUBLE PRECISION,humidity_min DOUBLE PRECISION,humidity_max DOUBLE PRECISION,light_limit_lux DOUBLE PRECISION,hazard_class TEXT NOT NULL DEFAULT '',monitoring_required BOOLEAN NOT NULL DEFAULT FALSE,notes TEXT NOT NULL DEFAULT '',created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_equipment_assets(id UUID PRIMARY KEY,asset_code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,category TEXT NOT NULL,manufacturer TEXT NOT NULL DEFAULT '',model TEXT NOT NULL DEFAULT '',serial_number TEXT NOT NULL DEFAULT '',owner_id TEXT NOT NULL DEFAULT '',custodian_id TEXT NOT NULL DEFAULT '',responsible_team TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'in_service',serviceability_status TEXT NOT NULL DEFAULT 'serviceable',calibration_required BOOLEAN NOT NULL DEFAULT FALSE,calibration_interval_days INTEGER,last_calibration_at TEXT NOT NULL DEFAULT '',next_calibration_at TEXT NOT NULL DEFAULT '',maintenance_interval_days INTEGER,last_maintenance_at TEXT NOT NULL DEFAULT '',next_maintenance_at TEXT NOT NULL DEFAULT '',warranty_until TEXT NOT NULL DEFAULT '',service_provider TEXT NOT NULL DEFAULT '',location_id UUID REFERENCES ops_locations(id),image_path TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_asset_documents(id UUID PRIMARY KEY,asset_id UUID NOT NULL REFERENCES ops_equipment_assets(id) ON DELETE CASCADE,document_type TEXT NOT NULL,title TEXT NOT NULL,file_path TEXT NOT NULL,mime_type TEXT NOT NULL DEFAULT '',version TEXT NOT NULL DEFAULT '',effective_at TEXT NOT NULL DEFAULT '',expires_at TEXT NOT NULL DEFAULT '',checksum TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_maintenance_events(id UUID PRIMARY KEY,asset_id UUID NOT NULL REFERENCES ops_equipment_assets(id) ON DELETE CASCADE,maintenance_type TEXT NOT NULL,status TEXT NOT NULL,scheduled_start TEXT NOT NULL DEFAULT '',scheduled_end TEXT NOT NULL DEFAULT '',performed_start TEXT NOT NULL DEFAULT '',performed_end TEXT NOT NULL DEFAULT '',provider TEXT NOT NULL DEFAULT '',technician TEXT NOT NULL DEFAULT '',cost DOUBLE PRECISION NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'EUR',result TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',evidence_document_id UUID REFERENCES ops_asset_documents(id),created_by TEXT NOT NULL,created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_calibration_events(id UUID PRIMARY KEY,asset_id UUID NOT NULL REFERENCES ops_equipment_assets(id) ON DELETE CASCADE,status TEXT NOT NULL,standard_reference TEXT NOT NULL DEFAULT '',method TEXT NOT NULL DEFAULT '',tolerance TEXT NOT NULL DEFAULT '',measured_deviation TEXT NOT NULL DEFAULT '',result TEXT NOT NULL DEFAULT '',performed_at TEXT NOT NULL DEFAULT '',valid_until TEXT NOT NULL DEFAULT '',provider TEXT NOT NULL DEFAULT '',technician TEXT NOT NULL DEFAULT '',certificate_document_id UUID REFERENCES ops_asset_documents(id),impact_assessment TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',created_by TEXT NOT NULL,created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_building_drawings(id UUID PRIMARY KEY,location_id UUID REFERENCES ops_locations(id),title TEXT NOT NULL,source_format TEXT NOT NULL,file_path TEXT NOT NULL,preview_path TEXT NOT NULL DEFAULT '',version TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'active',effective_at TEXT NOT NULL DEFAULT '',superseded_at TEXT NOT NULL DEFAULT '',width DOUBLE PRECISION,height DOUBLE PRECISION,metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_by TEXT NOT NULL,created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_drawing_markers(id UUID PRIMARY KEY,drawing_id UUID NOT NULL REFERENCES ops_building_drawings(id) ON DELETE CASCADE,location_id UUID REFERENCES ops_locations(id),asset_id UUID REFERENCES ops_equipment_assets(id),marker_code TEXT NOT NULL,label TEXT NOT NULL DEFAULT '',x DOUBLE PRECISION NOT NULL,y DOUBLE PRECISION NOT NULL,width DOUBLE PRECISION NOT NULL DEFAULT 0,height DOUBLE PRECISION NOT NULL DEFAULT 0,geometry_json JSONB NOT NULL DEFAULT '{}'::jsonb,created_at_us BIGINT NOT NULL,updated_at_us BIGINT NOT NULL)""",
"""CREATE TABLE IF NOT EXISTS ops_asset_movements(id UUID PRIMARY KEY,asset_id UUID NOT NULL REFERENCES ops_equipment_assets(id) ON DELETE CASCADE,from_location_id UUID REFERENCES ops_locations(id),to_location_id UUID REFERENCES ops_locations(id),moved_at TEXT NOT NULL,reason TEXT NOT NULL DEFAULT '',condition_before TEXT NOT NULL DEFAULT '',condition_after TEXT NOT NULL DEFAULT '',moved_by TEXT NOT NULL,confirmed_by TEXT NOT NULL DEFAULT '',created_at_us BIGINT NOT NULL)""",
]
    def ensure_schema(self):
        with self._connect() as connection:
            with connection.cursor() as cursor:
                for statement in self.statements():
                    cursor.execute(statement)
