apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fieldora
resources:
  - namespace.yaml
  - platform.yaml
  - ingress.yaml
  - network-policy.yaml
commonLabels:
  app.kubernetes.io/part-of: fieldora
