"""Initial authoritative relational schema."""

from natureai_next.infrastructure.database.migrations.core import Migration

SQL = r"""
CREATE TABLE library_info(id INTEGER PRIMARY KEY CHECK(id=1), public_id TEXT NOT NULL UNIQUE, created_at_us INTEGER NOT NULL, current_schema_version INTEGER NOT NULL, minimum_app_version TEXT NOT NULL, display_name TEXT NOT NULL, default_locale TEXT NOT NULL, active_taxonomy_release_ids_json TEXT NOT NULL DEFAULT '[]', integrity_state TEXT NOT NULL DEFAULT 'clean');
CREATE TABLE assets(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, media_type TEXT NOT NULL CHECK(media_type IN ('image')), lifecycle_state TEXT NOT NULL CHECK(lifecycle_state IN ('active','trashed','purged')), primary_file_instance_id INTEGER, capture_time_utc_us INTEGER, capture_local_text TEXT, capture_timezone TEXT, capture_time_certainty TEXT, capture_date_precision TEXT, rating INTEGER CHECK(rating BETWEEN 0 AND 5), color_label TEXT, pick_state TEXT, title TEXT, caption TEXT, user_notes TEXT, created_at_us INTEGER NOT NULL, modified_at_us INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>=1), FOREIGN KEY(primary_file_instance_id) REFERENCES file_instances(id) DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE file_instances(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, storage_mode TEXT NOT NULL CHECK(storage_mode IN ('managed','referenced','derivative')), role TEXT NOT NULL CHECK(role IN ('original','alternate','sidecar','preview','thumbnail','export')), normalized_path TEXT NOT NULL, path_key TEXT NOT NULL, file_size INTEGER NOT NULL CHECK(file_size>=0), modified_at_observed_us INTEGER, sha256 TEXT CHECK(sha256 IS NULL OR (length(sha256)=64 AND sha256=lower(sha256))), fast_fingerprint TEXT, availability_state TEXT NOT NULL CHECK(availability_state IN ('available','missing','offline','corrupt')), mime_type TEXT, format_name TEXT, import_source_path TEXT, verified_at_us INTEGER, created_at_us INTEGER NOT NULL, modified_at_us INTEGER NOT NULL);
CREATE UNIQUE INDEX ux_file_instances_active_path ON file_instances(path_key) WHERE availability_state!='missing';
CREATE INDEX ix_file_instances_hash ON file_instances(sha256) WHERE sha256 IS NOT NULL;
CREATE INDEX ix_assets_lifecycle_capture ON assets(lifecycle_state,capture_time_utc_us,id);
CREATE INDEX ix_assets_rating ON assets(rating,id);
CREATE INDEX ix_assets_modified ON assets(modified_at_us,id);
CREATE TABLE metadata_snapshots(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, file_instance_id INTEGER NOT NULL REFERENCES file_instances(id) ON DELETE CASCADE, encoding TEXT NOT NULL, payload BLOB NOT NULL CHECK(length(payload)<=16777216), payload_checksum TEXT NOT NULL, created_at_us INTEGER NOT NULL);
CREATE TABLE image_properties(id INTEGER PRIMARY KEY, asset_id INTEGER UNIQUE REFERENCES assets(id) ON DELETE CASCADE, file_instance_id INTEGER REFERENCES file_instances(id) ON DELETE CASCADE, pixel_width INTEGER NOT NULL CHECK(pixel_width>0), pixel_height INTEGER NOT NULL CHECK(pixel_height>0), orientation INTEGER, bit_depth INTEGER, color_space TEXT, has_alpha INTEGER NOT NULL DEFAULT 0 CHECK(has_alpha IN (0,1)), camera_make TEXT, camera_model TEXT, lens TEXT, exposure_json TEXT, metadata_snapshot_id INTEGER REFERENCES metadata_snapshots(id), CHECK(asset_id IS NOT NULL OR file_instance_id IS NOT NULL));
CREATE TABLE tags(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, normalized_name TEXT NOT NULL, display_name TEXT NOT NULL, parent_tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE, color TEXT, created_at_us INTEGER NOT NULL);
CREATE UNIQUE INDEX ux_tags_parent_name ON tags(COALESCE(parent_tag_id,0),normalized_name COLLATE NOCASE);
CREATE TABLE asset_tags(asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE, source TEXT NOT NULL CHECK(source IN ('user','import','plugin')), created_at_us INTEGER NOT NULL, PRIMARY KEY(asset_id,tag_id,source));
CREATE TABLE collections(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, collection_type TEXT NOT NULL CHECK(collection_type IN ('manual','smart')), name TEXT NOT NULL COLLATE NOCASE, description TEXT, smart_query_json TEXT, query_schema_version INTEGER, sort_mode TEXT NOT NULL, created_at_us INTEGER NOT NULL, modified_at_us INTEGER NOT NULL, CHECK((collection_type='manual' AND smart_query_json IS NULL) OR (collection_type='smart' AND smart_query_json IS NOT NULL AND query_schema_version IS NOT NULL)));
CREATE UNIQUE INDEX ux_collections_name ON collections(name);
CREATE TABLE collection_assets(collection_id INTEGER NOT NULL REFERENCES collections(id) ON DELETE CASCADE, asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, position_key TEXT NOT NULL, added_at_us INTEGER NOT NULL, PRIMARY KEY(collection_id,asset_id));
CREATE INDEX ix_collection_assets_position ON collection_assets(collection_id,position_key,asset_id);
CREATE TABLE locations(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, latitude REAL NOT NULL CHECK(latitude BETWEEN -90 AND 90), longitude REAL NOT NULL CHECK(longitude BETWEEN -180 AND 180), altitude_m REAL, accuracy_m REAL CHECK(accuracy_m IS NULL OR accuracy_m>=0), country_code TEXT, admin_area_1 TEXT, admin_area_2 TEXT, locality TEXT, place_name TEXT, source TEXT NOT NULL, confidence REAL, geometry_ref TEXT, created_at_us INTEGER NOT NULL);
CREATE VIRTUAL TABLE location_rtree USING rtree(id,min_lat,max_lat,min_lon,max_lon);
CREATE TRIGGER locations_ai AFTER INSERT ON locations BEGIN INSERT INTO location_rtree VALUES(new.id,new.latitude,new.latitude,new.longitude,new.longitude); END;
CREATE TRIGGER locations_ad AFTER DELETE ON locations BEGIN DELETE FROM location_rtree WHERE id=old.id; END;
CREATE TRIGGER locations_au AFTER UPDATE OF latitude,longitude ON locations BEGIN UPDATE location_rtree SET min_lat=new.latitude,max_lat=new.latitude,min_lon=new.longitude,max_lon=new.longitude WHERE id=new.id; END;
CREATE TABLE asset_locations(asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, location_id INTEGER NOT NULL REFERENCES locations(id), role TEXT NOT NULL CHECK(role IN ('capture','subject','user_defined')), precedence INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(asset_id,location_id,role));
CREATE TABLE taxonomy_sources(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, name TEXT NOT NULL, source_version TEXT NOT NULL, package_checksum TEXT NOT NULL, license_json TEXT NOT NULL, installed_at_us INTEGER NOT NULL, activated_at_us INTEGER, active INTEGER NOT NULL DEFAULT 0 CHECK(active IN(0,1)), UNIQUE(name,source_version));
CREATE TABLE taxa(id INTEGER PRIMARY KEY, source_id INTEGER NOT NULL REFERENCES taxonomy_sources(id) ON DELETE CASCADE, source_taxon_id TEXT NOT NULL, public_id TEXT NOT NULL UNIQUE, scientific_name TEXT NOT NULL, authorship TEXT, rank TEXT NOT NULL, parent_taxon_id INTEGER REFERENCES taxa(id), accepted_taxon_id INTEGER REFERENCES taxa(id), status TEXT NOT NULL, kingdom TEXT, major_group TEXT, extinct INTEGER NOT NULL DEFAULT 0 CHECK(extinct IN(0,1)), UNIQUE(source_id,source_taxon_id));
CREATE INDEX ix_taxa_parent ON taxa(parent_taxon_id); CREATE INDEX ix_taxa_accepted ON taxa(accepted_taxon_id); CREATE INDEX ix_taxa_rank ON taxa(rank); CREATE INDEX ix_taxa_source_name ON taxa(source_id,scientific_name);
CREATE TABLE taxon_closure(ancestor_taxon_id INTEGER NOT NULL REFERENCES taxa(id) ON DELETE CASCADE, descendant_taxon_id INTEGER NOT NULL REFERENCES taxa(id) ON DELETE CASCADE, depth INTEGER NOT NULL CHECK(depth>=0), PRIMARY KEY(ancestor_taxon_id,descendant_taxon_id));
CREATE TABLE taxon_names(id INTEGER PRIMARY KEY, taxon_id INTEGER NOT NULL REFERENCES taxa(id) ON DELETE CASCADE, language_tag TEXT, region_code TEXT, name TEXT NOT NULL, name_type TEXT NOT NULL, preferred INTEGER NOT NULL DEFAULT 0 CHECK(preferred IN(0,1)), source TEXT NOT NULL);
CREATE TABLE taxon_regions(taxon_id INTEGER NOT NULL REFERENCES taxa(id) ON DELETE CASCADE, region_code TEXT NOT NULL, occurrence_status TEXT, source TEXT NOT NULL, PRIMARY KEY(taxon_id,region_code,source));
CREATE TABLE user_taxa(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, scientific_name TEXT, display_name TEXT NOT NULL, rank TEXT, mapped_taxon_id INTEGER REFERENCES taxa(id), created_at_us INTEGER NOT NULL, modified_at_us INTEGER NOT NULL);
CREATE TABLE regions_of_interest(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, shape_type TEXT NOT NULL, coordinates_json TEXT NOT NULL CHECK(json_valid(coordinates_json)), label TEXT, created_source TEXT NOT NULL, created_at_us INTEGER NOT NULL, modified_at_us INTEGER NOT NULL);
CREATE TABLE observations(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, taxon_id INTEGER REFERENCES taxa(id), user_taxon_id INTEGER REFERENCES user_taxa(id), observation_type TEXT NOT NULL CHECK(observation_type IN ('organism','habitat','landscape','unknown')), life_stage TEXT, sex TEXT, count INTEGER CHECK(count IS NULL OR count>=0), behavior TEXT, notes TEXT, confirmation_state TEXT NOT NULL, source TEXT NOT NULL CHECK(source IN ('user','import','plugin')), region_of_interest_id INTEGER REFERENCES regions_of_interest(id), created_at_us INTEGER NOT NULL, modified_at_us INTEGER NOT NULL, revision INTEGER NOT NULL DEFAULT 1, CHECK(NOT(taxon_id IS NOT NULL AND user_taxon_id IS NOT NULL)));
CREATE INDEX ix_observations_asset ON observations(asset_id); CREATE INDEX ix_observations_taxon ON observations(taxon_id);
CREATE TABLE model_packages(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, model_identity TEXT NOT NULL, semantic_version TEXT NOT NULL, model_family TEXT NOT NULL, artifact_checksum TEXT NOT NULL, manifest_json TEXT NOT NULL CHECK(json_valid(manifest_json)), license_json TEXT NOT NULL, install_path_token TEXT NOT NULL, installation_state TEXT NOT NULL, installed_at_us INTEGER, UNIQUE(model_identity,semantic_version));
CREATE TABLE model_variants(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, package_id INTEGER NOT NULL REFERENCES model_packages(id) ON DELETE CASCADE, variant_identity TEXT NOT NULL, runtime TEXT NOT NULL CHECK(runtime IN ('torch','onnx')), precision TEXT NOT NULL, device_requirements_json TEXT NOT NULL, preprocessing_identity TEXT NOT NULL, embedding_dimension INTEGER, active INTEGER NOT NULL DEFAULT 0 CHECK(active IN(0,1)), UNIQUE(package_id,variant_identity));
CREATE TABLE jobs(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, job_type TEXT NOT NULL, payload_version INTEGER NOT NULL, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), state TEXT NOT NULL, priority INTEGER NOT NULL DEFAULT 0, resource_class TEXT NOT NULL, idempotency_key TEXT UNIQUE, parent_job_id INTEGER REFERENCES jobs(id), dependency_job_id INTEGER REFERENCES jobs(id), progress_current INTEGER NOT NULL DEFAULT 0, progress_total INTEGER, progress_unit TEXT, progress_message TEXT, attempt_count INTEGER NOT NULL DEFAULT 0, retry_at_us INTEGER, created_at_us INTEGER NOT NULL, started_at_us INTEGER, completed_at_us INTEGER, modified_at_us INTEGER NOT NULL, error_code TEXT, diagnostic_reference TEXT, result_json TEXT);
CREATE INDEX ix_jobs_dispatch ON jobs(state,priority DESC,retry_at_us,created_at_us);
CREATE TABLE job_items(id INTEGER PRIMARY KEY, job_id INTEGER NOT NULL REFERENCES jobs(id) ON DELETE CASCADE, item_key TEXT NOT NULL, state TEXT NOT NULL, attempt_count INTEGER NOT NULL DEFAULT 0, payload_json TEXT, result_json TEXT, error_code TEXT, modified_at_us INTEGER NOT NULL, UNIQUE(job_id,item_key));
CREATE TABLE inference_runs(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, job_id INTEGER REFERENCES jobs(id), model_variant_id INTEGER NOT NULL REFERENCES model_variants(id), execution_provider TEXT NOT NULL, parameter_json TEXT NOT NULL CHECK(json_valid(parameter_json)), application_version TEXT NOT NULL, started_at_us INTEGER NOT NULL, completed_at_us INTEGER, outcome TEXT, error_code TEXT);
CREATE TABLE embeddings(id INTEGER PRIMARY KEY, asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE, model_variant_id INTEGER NOT NULL REFERENCES model_variants(id), preprocessing_identity TEXT NOT NULL, region_of_interest_id INTEGER REFERENCES regions_of_interest(id), vector_dimension INTEGER NOT NULL, scalar_type TEXT NOT NULL, normalized INTEGER NOT NULL CHECK(normalized IN(0,1)), vector_blob BLOB NOT NULL, vector_checksum TEXT NOT NULL, created_at_us INTEGER NOT NULL, UNIQUE(asset_id,model_variant_id,preprocessing_identity,region_of_interest_id));
CREATE INDEX ix_embeddings_model ON embeddings(model_variant_id,preprocessing_identity,asset_id);
CREATE TABLE ai_suggestions(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, asset_id INTEGER REFERENCES assets(id), observation_id INTEGER REFERENCES observations(id), inference_run_id INTEGER NOT NULL REFERENCES inference_runs(id), suggestion_type TEXT NOT NULL, candidate_taxon_id INTEGER REFERENCES taxa(id), candidate_label TEXT, raw_score REAL NOT NULL, rank INTEGER NOT NULL, calibrated_score REAL, calibration_identity TEXT, provenance_json TEXT NOT NULL CHECK(json_valid(provenance_json)), review_state TEXT NOT NULL CHECK(review_state IN ('pending','accepted','rejected','superseded')), reviewed_at_us INTEGER, user_action_public_id TEXT, CHECK(asset_id IS NOT NULL OR observation_id IS NOT NULL));
CREATE TABLE event_outbox(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, event_type TEXT NOT NULL, schema_version INTEGER NOT NULL, aggregate_public_id TEXT, payload_json TEXT NOT NULL CHECK(json_valid(payload_json)), created_at_us INTEGER NOT NULL, dispatch_state TEXT NOT NULL DEFAULT 'pending', attempt_count INTEGER NOT NULL DEFAULT 0);
CREATE INDEX ix_outbox_dispatch ON event_outbox(dispatch_state,created_at_us,id);
CREATE TABLE audit_log(id INTEGER PRIMARY KEY, public_id TEXT NOT NULL UNIQUE, actor TEXT NOT NULL, action_type TEXT NOT NULL, target_public_id TEXT NOT NULL, before_json TEXT, after_json TEXT, created_at_us INTEGER NOT NULL, correlation_id TEXT NOT NULL);
CREATE INDEX ix_audit_target ON audit_log(target_public_id,created_at_us);
CREATE TABLE installed_plugins(id INTEGER PRIMARY KEY, plugin_id TEXT NOT NULL UNIQUE, version TEXT NOT NULL, manifest_checksum TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN(0,1)), compatibility_status TEXT NOT NULL, granted_capabilities_json TEXT NOT NULL CHECK(json_valid(granted_capabilities_json)), installed_at_us INTEGER NOT NULL, last_load_result_json TEXT);
"""
MIGRATION = Migration(1, "initial_core_schema", SQL)
